# Generated by Django 2.2.16 on 2023-06-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200118_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('WL', 'WELCOME'), ('AL', 'ALERT')], default=('WL', 'WELCOME'), max_length=2),
        ),
    ]
