# Generated by Django 2.2.16 on 2023-06-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=None, null=True),
        ),
    ]
